Separate test and format command in develop (#157)
Because we generally do not want to check formatting
during test. In other words, most of the developers
just want to test it only with test command.

So I separate test and format command in development
environment. But CI test should run with format
test.

As a result, developers can test only with test command
in development environment.
When developer want to pull request, they must fix
formatting issue.

ISSUE=#155

diff --git a/bootstrap/command/lint b/bootstrap/command/lint
--- a/bootstrap/command/lint
+++ b/bootstrap/command/lint
@@ -16,5 +16,18 @@
 
 . $BACARDI_PATH/bootstrap/common/path_info.sh
 
-mocha --napi-modules examples/calculator.js
-node --napi-modules $(bacardi_path)/node_modules/jest/bin/jest.js --verbose
+function need_to_format() {
+  result=$($(bootstrap_command_path)/format --diff)
+  if [ "$result" = "no modified files to format" ] \
+      || [ "$result" = "clang-format did not modify any files" ]; then
+    return 1
+  else
+    echo "$result"
+    return 0
+  fi
+}
+
+if need_to_format; then
+  echo "lint error: You can fix the lint error with |bacardi format| command."
+  exit 1
+fi
